version: '3.8'

services:
  frontend:
    build: ../client/safe_front  # Указываем путь к папке фронта
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_HOST=http://spring_app:8080
    depends_on:
      - app

  app:
    build: .
    container_name: spring_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/safety?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: safety
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
