version: '3.8'

services:
  backend:
    image: my-backend
    build:
      context: .
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/safety
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - /home/user/photos:/app/photos  # <== Привязываем папку сервера к контейнеру
    depends_on:
      - db


#  frontend:
#    image: my-frontend
#    build:
#      context: ./frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: safety
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
