spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      add-mappings: true
      static-locations: file:/root/images/
  datasource:
 #   url: jdbc:mysql://127.0.0.1:3306/safety
    url: jdbc:mysql://217.114.3.39:3306/safety
   # url: jdbc:mysql://db:3306/safety
    username: root
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8080

category:
  risk: Термические, Химические, Механические
  ef: Сокращение, Увеличение

photo:
#  url: C:\Users\e.khisamutdinov\IdeaProjects\demo\src\main\resources\static\images
  url:
#    load: C:\Users\e.khisamutdinov\IdeaProjects\demo\src\main\resources\static\images/
#    upload: C:\Users\e.khisamutdinov\IdeaProjects\demo\src\main\resources\static\images/
    load: /root/client/safe_front/public/images/
    upload: /images/

cors:
 # origins: ${CORS:http://yourrisk.ru:3000}
  origins: ${CORS:http://localhost:3000}


bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 3600000



#время жизни токена на фронте и бэке
#страница риска
#страница человека
#топменю справа кнопки
#https nginx
#хранение фото на сервере не в папке с проектом
#валидация полей при создании риска
#topbar поуже
#снизу 3 кнопки
#перенести кнопку добавитьвниз

